### ISSUE TITLE
Request: enable by default

### ISSUE THREAD

**Issue by mistamichal** [Varriount/fvtt-autorotate#1]
Can you enable this on tokens by default. As the GM it's annoying to have to go through all my tokens and enable it for each one.
Cheers

**Comment by Varriount** [comment]
Hm, but what about those who want it enabled by default?

**Comment by mistamichal** [comment]
Ok, in that case, how about a global on/off?

**Comment by hhu94** [comment]
Considering most of your users will be former About Face users, it doesn't make sense to change the default behavior they would expect from that module.

I will personally wait until there is a way to turn auto rotation on for all tokens before switching over.

**Comment by Varriount** [comment]
@mistamichal 
> 
> 
> Ok, in that case, how about a global on/off?

That's doable. I can add that in, though it's likely only going to be a temporary solution. As more features are added, people are going to want to set token defaults for various other settings too. A long term solution will either be a full sub-window for setting defaults, or recommending something like the Token Mold module.

@hhu94 
> 
> 
> Considering most of your users will be former About Face users, it doesn't make sense to change the default behavior they would expect from that module.
> 
> I will personally wait until there is a way to turn auto rotation on for all tokens before switching over.

I am not going to implement behavior just because About Face has it. While I appreciate calling to my attention the expectations of former users, in this case I feel quite strongly that maintaining the default token behavior on install is the optimal decision.

In any case, if you want to enable/disable autorotation on all tokens, just run this macro:
```javascript
(async function(){
  let content = `
    <form><div class="form-group">
      <label>Enable/Disable Autorotation for All Tokens:</label>
      <input type="checkbox" id="ar-enabled" value="0">
    </div></form>
  `;

  async function apply(html){
    let checked = html.find('#ar-enabled').is(':checked');
    console.log(`Setting autorotate.enabled flag to ${checked}`);

    for (let actor of game.actors){
      console.log({actor});
      console.log({'actor.data.token': actor.data.token});
      await actor.update({'data.token.flags.autorotate.enabled': checked});
    }

    for (let scene of game.scenes){
      await scene.view();
      for (let token of canvas.tokens.placeables){
        console.log({token});
        token.setFlag('autorotate', 'enabled', checked);
      }
    }

    console.log('Finished.');
  }

  new Dialog({
    content: content,
    buttons: {
      apply: {
        label: "Apply",
        callback: async (html) => {
          try {
            apply(html);
            ui.notifications.info("Success");
          } catch {
            ui.notifications.error("Error. Check console (F12).");
          }
        }
      },
      cancel: {
        label: "Cancel",
      }
    }
  }).render(true);

}())
```

**Comment by PaulWRoberts** [comment]
I got to second this. Would love there to be an option to allow all tokens have this on by default, I love that there is functionality to face the target, which is not in about face and makes this potentially better. However, without the ability to apply this to all new enemies I drop it is far too tedious to use. I recommend a check box on settings to choose the default behavior.
